#!/usr/bin/env python
import argparse
import os
import textwrap
from pathlib import Path
parser = argparse.ArgumentParser()

parser.add_argument("xyz_files", nargs="+", help="The xyz file(s) for embedding")
parser.add_argument("--cpus", help="Number of CPUs for calculation", type=int, default=8)
parser.add_argument("--mem", help="Mb of memory available", type=int, default=16000)
parser.add_argument("--partition", help="HPC partition to run calculations on", type=str, default="kemi1")

def qsub_prep(xyz_file, cpus, mem, partition):
    """
    Submission script for xyz file embedding
    Takes an xyz file - generates N conformers; outputs lowest energy conformer.
    """
    pwd = os.getcwd()
    xyz_stem = Path(xyz_file).stem
    slurm_filename = f"submit_{xyz_stem}.slurm"
    qsub_file="""#!/bin/sh
#SBATCH --job-name={xyz_file}
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --ntasks={cpus}
#SBATCH --mem={mem}
#SBATCH --error={pwd}/{xyz_file}.err
#SBATCH --output={pwd}/{xyz_file}.out
#SBATCH --time=08:00:00
#SBATCH --partition={partition}
#SBATCH --no-requeue
#micromamba activate Complex
#Move to scratch dir for calculations
cp {xyz_file} /scratch/$SLURM_JOB_ID/
ln -s /lustre/hpc/kemi/hteahan/Orca_workflow/scripts/TMC_embed /scratch/$SLURM_JOB_ID/TMC_embed
cp /lustre/hpc/kemi/hteahan/Orca_workflow/scripts/embed.py /scratch/$SLURM_JOB_ID/
ln -s /lustre/hpc/kemi/hteahan/opt/xtb-6.7.1/xtb-dist/bin/xtb /scratch/$SLURM_JOB_ID/xtb
cd /scratch/$SLURM_JOB_ID/


#Run calculations
micromamba run -n Complex python embed.py {xyz_file} --xtb_path /scratch/$SLURM_JOB_ID/xtb
cp -r INPUT {pwd}
    """.format(mem=mem, cpus=cpus, pwd=pwd, partition=partition, xyz_file=xyz_file)
    
    with open(slurm_filename, "w") as f:
        f.write(textwrap.dedent(qsub_file))
    return slurm_filename


if __name__=="__main__":
    args = parser.parse_args()
    #inp_file = args.inp_file
    cpus = args.cpus
    mem = args.mem
    partition = args.partition
    #curate_inp(inp_file, cpus, mem)
    #qsub_name = qsub_prep(inp_file, cpus, mem, partition)
    for inp_file in args.xyz_files:
        qsub_name = qsub_prep(inp_file, cpus, mem, partition)
        #Run process
        os.popen("sbatch {0}".format(qsub_name)).read()

