#!/usr/bin/env python3

import argparse
from pathlib import Path

def main():
    '''
    Operates in given directory, converting all .xyz files to the desired custom .inp file
    for use with Orca or similar programs.

    Using the parser, any custom arguments can be added, and lines can also be removed.
    '''
    parser = argparse.ArgumentParser()

    parser.add_argument(
            "xyz_files",
            nargs="+",
            help = "Input XYZ files; one or more"
            )
    parser.add_argument(
            "--header",
            default = "!r2scan-3c opt freq",
            help ="Orca header line. Default is optimization and frequency calculation using r2scan-3c"
            )
    parser.add_argument(
            "--keep_lines",
            default = 2,
            help = """When processing the .xyz file it is often desired to remove the first two lines, as they contain
            artifacts unrelated to the .inp file. Therefore, use this to remove as many lines as necessary."""
            )
    parser.add_argument(
            "--charge",
            default = 0,
            help = "Molecular charge"
            )
    parser.add_argument(
            "--multiplicity",
            default = 1,
            help = "Multiplicity of molecule - 2S+1 (S = charge)"
            )






    args = parser.parse_args()

    for file in args.xyz_files:
        if file[-4:] == ".xyz":
            with open(file, "r") as f:
                txt = f.readlines()
                txt = txt[int(args.keep_lines):] #skipfirst two lines
                txt = "".join(txt)
                query = args.header
                # query = f"!r2scan-3c opt freq \n \n * XYZ {args.charge} {args.multiplicity} \n"
                buffer = f"\n \n * XYZ {args.charge} {args.multiplicity} \n"
                inp = query + buffer + txt + f"\n *"
                
                xyz_path = Path(file)
                out = Path(".") / f"{xyz_path.stem}.inp"
                print(f"Wrote {out} :-)")
                out.write_text(inp)

if __name__=="__main__":
    main()

